<a href="https://colab.research.google.com/github/tonisun/Python-DataScience-MachineLearning/blob/master/TensorFlow2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <a id='0'>[<img align="left" src="https://dev.egosanto.de/images/back2.png" width='40'>](#0)</a> TensorFlow 2.x

<img align='right' src='https://i1.wp.com/talkai.blog/wp-content/uploads/2019/03/tensorflow-2.0.jpg?zoom=2&resize=1068%2C694' width='550'/>

## Content
- [TensorFlow 2.0 Introduction](#1)
- [Importing TensorFlow](#2)
- [Tensors](#3)
  - [Introduction to Tensor Variables `tf.Variables()`](#3.1)
    - [Creating Tensors with Type](#3.1.1)    
  - [Rank/Degree of Tensors](#3.2)
  - [Shape of Tensors](#3.3)
  - [Changing Shape](#3.4)
  - [Slicing Tensors](#3.5)
  - [Types of Tensors](#3.6)


## [<img align="left" id="0" src="https://dev.egosanto.de/images/back2.png" width=40>](#0) TensorFlow 2.0 Introduction<a id="1"></a>

- https://www.tensorflow.org/guide
- https://www.tensorflow.org/tutorials

To install TensorFlow on your local machine you can use pip.
```console
pip install tensorflow
```
![alt text](https://)If you have a CUDA enabled GPU you can install the GPU version of TensorFlow. You will also need to install some other software which can be found here: 
- https://www.tensorflow.org/install/gpu 
```console
pip install tensorflow-gpu
```


## [<img align="left" id="0" src="https://dev.egosanto.de/images/back2.png" width=40>](#0) Importing TensorFlow<a id="2"></a><br>

In [ ]:
%tensorflow_version 2.x

In [ ]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


## [<img align="left" id="0" src="https://dev.egosanto.de/images/back2.png" width=40>](#0) Tensors<a id="3"></a>

Tensor is a Scalar, Vector if has one value in.

- https://en.wikipedia.org/wiki/Tensor
- https://www.tensorflow.org/guide/tensor

Each tensor has a data type and a shape. 

**Data Types Include**: float32, int32, string and others.

**Shape**: Represents the dimension of data.

Just like vectors and matrices tensors can have operations applied to them like addition, subtraction, dot product, cross product etc.

### [<img align="left" id="0" src="https://dev.egosanto.de/images/back2.png" width=40>](#0) Creating Variables `tf.Variables()`<a id="3.1"></a>

- https://www.tensorflow.org/guide/variable
- https://www.tensorflow.org/api_docs/python/tf/dtypes
- https://de.mathworks.com/company/newsletters/articles/what-is-int8-quantization-and-why-is-it-popular-for-deep-neural-networks.html

In [ ]:
v1 = tf.Variable(2147483647)
v1
# <tf.Variable 'Variable:0' shape=(1, 1) dtype=int32, numpy=array(2147483647, dtype=int32)>
# for my System is default int Type 32 Bit (dtype=int32)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2147483647>

In [ ]:
# A scalar, shape: []
v1.shape

TensorShape([])

In [ ]:
# Rank = 0
tf.rank(v1)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

Represents the type of the elements in a Tensor.

The following DType objects are defined:
* `tf.float16`: 16-bit half-precision floating-point.  
* `tf.float32`: 32-bit single-precision floating-point.  
* `tf.float64`: 64-bit double-precision floating-point.  
* `tf.bfloat16`: 16-bit truncated floating-point.  
* `tf.complex64`: 64-bit single-precision complex.  
* `tf.complex128`: 128-bit double-precision complex.  
* `tf.int8`: 8-bit signed integer.  
* `tf.uint8`: 8-bit unsigned integer.  
* `tf.uint16`: 16-bit unsigned integer.  
* `tf.uint32`: 32-bit unsigned integer.  
* `tf.uint64`: 64-bit unsigned integer.  
* `tf.int16`: 16-bit signed integer.  
* `tf.int32`: 32-bit signed integer.  
* `tf.int64`: 64-bit signed integer.  
* `tf.bool`: Boolean.  
* `tf.string`: String.  
* `tf.qint8`: Quantized 8-bit signed integer.  
* `tf.quint8`: Quantized 8-bit unsigned integer.  
* `tf.qint16`: Quantized 16-bit signed integer.  
* `tf.quint16`: Quantized 16-bit unsigned integer.  
* `tf.qint32`: Quantized 32-bit signed integer.  
* `tf.resource`: Handle to a mutable resource.  
* `tf.variant`: Values of arbitrary types.  

The tf.as_dtype() function converts numpy types and string type names to a DType object.

|Bit|Name|Sign|min .. max|Decimal places|
|---|---|---|---|---|
|8|`int8`|signed|`-128` .. `127`|3|
|8|`qint8`|signed|`-128` .. `127`|3|
|8|`uint8`|unsigned|`0` .. `255`|3|
|8|`quint8`|unsigned|`0` .. `255`|3|

### Rank 0

In [ ]:
# tf Datatype 8 Bit int int8(-128 .. 127)
# tf 
v2 = tf.Variable(0,dtype=tf.quint8)
v2

<tf.Variable 'Variable:0' shape=() dtype=quint8, numpy=0>

In [ ]:
# A scalar, shape: []
v2.shape

TensorShape([])

In [ ]:
# Rank = 0
tf.rank(v2)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

### [<img align="left" id="0" src="https://dev.egosanto.de/images/back2.png" width=40>](#0) Creating Constants `tf.constant()`<a id="3.2"></a>

In [ ]:
c1 = tf.constant( 3.14)
c1

<tf.Tensor: shape=(), dtype=float32, numpy=3.14>

In [ ]:
# A scalar, shape: []
c1.shape

TensorShape([])

In [ ]:
# Rank = 0
tf.rank(c1)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

#### [<img align="left" id="0" src="https://dev.egosanto.de/images/back2.png" width=40>](#0) Creating Tensors with Type<a id="3.1.1"></a> 

For a full list of datatypes please refer to the following guide.

- https://www.tensorflow.org/api_docs/python/tf/dtypes/DType?version=stable


### Rank 1

In [ ]:
v1 = tf.Variable([2.0,3.0,4.0])
v1

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>


<img src='https://www.tensorflow.org/guide/images/tensor/vector.png' width='150'/>

In [ ]:
# A vector, shape: [3]
v1.shape

TensorShape([3])

In [ ]:
# Rank = 1
tf.rank(v1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

### Rank 2

In [ ]:
v1 = tf.Variable([[1, 2],
                  [3, 4],
                  [5, 6]], dtype=tf.float16)
v1

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

<img src='https://www.tensorflow.org/guide/images/tensor/matrix.png' width='150'/>

In [ ]:
#A matrix, shape: [3, 2]
v1.shape

TensorShape([3, 2])

In [ ]:
# Rank = (2)
tf.rank(v1)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

### [<img align="left" id="0" src="https://dev.egosanto.de/images/back2.png" width=40>](#0) Rank/Degree of Tensors<a id="3.2"></a>